---
  - name: Instalando dependências mysql
    ansible.builtin.apt: 
      pkg:
      - mysql-server
      - python3-pymysql
      state: latest
      update_cache: yes
  
  - name: Criando tabela wordpress_db
    community.mysql.mysql_db:
      name: '{{ wp_db_name }}'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock

  - name: Criando usuário para a tabela do wordpress_db
    community.mysql.mysql_user:
      name: '{{ wp_db_user }}'
      password: "{{ wp_db_pwd }}"
      priv: '{{ wp_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
      host: '{{ item }}'
    with_items:
      - 'localhost'
      - '127.0.0.1'
      - "{{ db_allowed_host }}"
  
  - name: Permitindo acesso externo ao banco de dados
    ansible.builtin.replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: "127.0.0.1"
      replace: "0.0.0.0"
    notify:
      - restart mysql